sudo: false
language: ruby

rvm:
  - 2.3.0

branches:
  only:
    - master

env:
  global:
    secure: BPrTAYfL0Nr+F8vPP6IydLE/h5/DOYw8Tviked57VjzTAfGtGJ/Dp63LwpLVhPSU4SVPr90qft8Jp7EMW4iYEq7Tw/1KNjGejADNAU6Dw2uTe9fGkQ5uddj+uI+kPPFI5jeGAAN1t7MUUnhSkRhObhdHnC8r6Wj0J5OthAOh06A=
before_script:
  - npm install -g bower
  - bower install
  - git config --global user.email "will+git@drnd.me"
  - git config --global user.name "William Durand"
  - git remote rm origin
  - git remote add origin "https://willdurand:$GH_TOKEN@github.com/clermontech/planet.git"

script:
  - bundle exec compass compile
  - bundle exec jekyll build

deploy:
  skip_cleanup: true
  provider: script
  script: bash bin/publish
  on:
    branch: master
